services:
  - type: web
    name: beads-byshafaq
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd auth && python manage.py collectstatic --noinput
      cd auth && python manage.py migrate
    startCommand: cd auth && gunicorn auth.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: auth.settings
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/auth
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
