# render.yaml - configure Render deployment and database
services:
  - type: web
    name: authapp # replace with your app name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn auth.auth.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myshop-beads # database name in Render
          property: connectionString

databases:
  - name: myshop-beads # database name in Render
    plan: free # free plan for PostgreSQL
